
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glksgirkmdsduuuovvps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsa3NnaXJrbWRzZHV1dW92dnBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMjUzNTQsImV4cCI6MjA1NjgwMTM1NH0.De8q7uaWiH2oGtgFkKCWVYX3VJ839-MOUIXHHrcpaA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public',
  },
});
